import { useState } from 'react'
import { Note } from '@/lib/types'
import { Copy, Download, FileText, Check, Share2 } from 'lucide-react'
import { clsx } from 'clsx'

interface ExportBarProps {
  note: Note
}

export function ExportBar({ note }: ExportBarProps) {
  const [copied, setCopied] = useState(false)
  const [showToast, setShowToast] = useState(false)
  const [toastMessage, setToastMessage] = useState('')

  const showNotification = (msg: string) => {
    setToastMessage(msg)
    setShowToast(true)
    setTimeout(() => setShowToast(false), 2000)
  }

  const getSummaryText = () => {
    let text = `# ${note.title}\n\n`
    
    if (note.tldr) {
      text += `## TL;DR\n${note.tldr}\n\n`
    }

    if (note.key_points && note.key_points.length > 0) {
      text += `## Key Points\n`
      note.key_points.forEach((p, i) => { text += `${i + 1}. ${p}\n` })
      text += '\n'
    }

    if (note.bullet_summary?.length > 0) {
      text += `## Summary\n`
      note.bullet_summary.forEach(b => { text += `• ${b}\n` })
      text += '\n'
    }

    if (note.action_items && note.action_items.length > 0) {
      text += `## Action Items\n`
      note.action_items.forEach(a => { text += `☐ ${a}\n` })
      text += '\n'
    }

    if (note.keywords && note.keywords.length > 0) {
      text += `## Keywords\n${note.keywords.join(', ')}\n\n`
    }

    if (note.flashcards?.length > 0) {
      text += `## Flashcards\n`
      note.flashcards.forEach((f, i) => {
        text += `Q${i + 1}: ${f.question}\nA${i + 1}: ${f.answer}\n\n`
      })
    }

    if (note.timeline?.length > 0) {
      text += `## Timeline\n`
      note.timeline.forEach((t, i) => {
        text += `${i + 1}. ${t.step}: ${t.description}\n`
      })
      text += '\n'
    }

    text += `---\nGenerated by AI Summarizer • ${new Date(note.created_at).toLocaleDateString()}\n`
    return text
  }

  const handleCopy = async () => {
    try {
      await navigator.clipboard.writeText(getSummaryText())
      setCopied(true)
      showNotification('Summary copied to clipboard!')
      setTimeout(() => setCopied(false), 2000)
    } catch {
      showNotification('Failed to copy')
    }
  }

  const handleDownloadTxt = () => {
    const blob = new Blob([getSummaryText()], { type: 'text/plain' })
    const url = URL.createObjectURL(blob)
    const a = document.createElement('a')
    a.href = url
    a.download = `${note.title.replace(/[^a-z0-9]/gi, '_').toLowerCase()}_summary.txt`
    document.body.appendChild(a)
    a.click()
    document.body.removeChild(a)
    URL.revokeObjectURL(url)
    showNotification('Downloaded as TXT!')
  }

  const handleDownloadMd = () => {
    const blob = new Blob([getSummaryText()], { type: 'text/markdown' })
    const url = URL.createObjectURL(blob)
    const a = document.createElement('a')
    a.href = url
    a.download = `${note.title.replace(/[^a-z0-9]/gi, '_').toLowerCase()}_summary.md`
    document.body.appendChild(a)
    a.click()
    document.body.removeChild(a)
    URL.revokeObjectURL(url)
    showNotification('Downloaded as Markdown!')
  }

  const handleShare = async () => {
    const shareData = {
      title: note.title,
      text: note.tldr || note.bullet_summary?.[0] || 'AI Generated Summary',
      url: window.location.href,
    }
    try {
      if (navigator.share) {
        await navigator.share(shareData)
      } else {
        await navigator.clipboard.writeText(window.location.href)
        showNotification('Link copied to clipboard!')
      }
    } catch {
      // User cancelled share dialog
    }
  }

  return (
    <>
      {/* Toast notification */}
      {showToast && (
        <div className="fixed bottom-6 left-1/2 -translate-x-1/2 z-50 bg-card border border-border shadow-lg rounded-full px-5 py-2.5 text-sm font-medium animate-in slide-in-from-bottom-4 fade-in duration-300 flex items-center gap-2">
          <Check size={16} className="text-emerald-500" />
          {toastMessage}
        </div>
      )}

      {/* Export Bar */}
      <div className="flex items-center gap-2 flex-wrap">
        <button
          onClick={handleCopy}
          className={clsx(
            "flex items-center gap-2 px-4 py-2 rounded-lg text-sm font-medium transition-all duration-200 border",
            copied
              ? "bg-emerald-500/10 border-emerald-500/20 text-emerald-600 dark:text-emerald-400"
              : "bg-card border-border hover:border-primary/30 hover:bg-primary/5 text-foreground"
          )}
        >
          {copied ? <Check size={16} /> : <Copy size={16} />}
          {copied ? 'Copied!' : 'Copy'}
        </button>

        <button
          onClick={handleDownloadTxt}
          className="flex items-center gap-2 px-4 py-2 rounded-lg text-sm font-medium bg-card border border-border hover:border-primary/30 hover:bg-primary/5 transition-all duration-200"
        >
          <Download size={16} />
          TXT
        </button>

        <button
          onClick={handleDownloadMd}
          className="flex items-center gap-2 px-4 py-2 rounded-lg text-sm font-medium bg-card border border-border hover:border-primary/30 hover:bg-primary/5 transition-all duration-200"
        >
          <FileText size={16} />
          Markdown
        </button>

        <button
          onClick={handleShare}
          className="flex items-center gap-2 px-4 py-2 rounded-lg text-sm font-medium bg-card border border-border hover:border-primary/30 hover:bg-primary/5 transition-all duration-200"
        >
          <Share2 size={16} />
          Share
        </button>
      </div>
    </>
  )
}
